#-----------------------------------HEROKU CI/CD CODE-----------------------------------
#image: maven:
image: ubuntu:latest
cache:
  paths:
    - .m2/repository/Trip_Management_System_Group_16/
    - target/

before_script:
  - apt-get update
  - ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone
  - apt-get --yes --force-yes install wget curl maven git

stages:
  - build
  - test
  - code_quality
  - deploy
  - deploy-prod

build:
  image: maven:3-jdk-8
  stage: build
  script:
    - mvn clean package -DskipTests=true
    - ls
  artifacts:
    paths:
      - target/*.jar
  only:
    refs:
      - feature_configuration
      - feature_UI
      - feature_backend
      - develop
      - merge_requests
      - heroku_configuration
      - main

# test stage will compile the code and run all the unit tests present in the
# test folder.
test:
  image: maven:3-jdk-8
  stage: test
  script:
    - mvn clean test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
  only:
    refs:
      - feature_configuration
      - feature_UI
      - feature_backend
      - develop
      - merge_requests
      - heroku_configuration
      - main

code_quality:
  stage: code_quality
  variables:
    UPLOAD_QUALITY_REPORT: 'curl -X PUT -H "Authorization: Token $QSCORED_API_KEY" -H "repository-link: $CI_PROJECT_URL" + -H "username:bn489600@dal.ca" -H "Content-Type: mulitpart/form-data" --url "https://qscored.com/api/upload/file.xml?is_open_access=off&version=$CI_PIPELINE_IID&project_name=CSCI_5308_GROUP_16" -F "file=@Designite_output/DesigniteAnalysis.xml"'
  script:
    - wget -O DesigniteJava.jar https://www.dropbox.com/s/mwizkj8uhplz4x3/DesigniteJava.jar?dl=1
    - echo "/$CI_PROJECT_PATH"
    - ls -lrth
    #    - java -jar DesigniteJava.jar -i . -o Designite_output -f XML
    - java -jar DesigniteJava.jar -ci -repo $CI_PROJECT_PATH -pat $PAT -host "git.cs.dal.ca"
    - 'eval "$UPLOAD_QUALITY_REPORT"'
  only:
    refs:
      - feature_configuration
      - feature_UI
      - feature_backend
      - develop
      - merge_requests
      - code_quality_danny
      - heroku_configuration
      - ride_share_benny
      - main

deploy-prod:
  image: ruby:latest
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  #TODO: Add Production App Environment Variables
  only:
    - main

deploy:
  image: ruby:latest
  stage: deploy
  #  tags:
  #    - ugrad
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - heroku_configuration
    - main